version : '3'

services:

  server:
    build: ./server
    expose: 
      - ${APP_SERVER_PORT}
    environment: 
      API_HOST: ${API_HOST} 
      API_SERVER_PORT: ${APP_SERVER_PORT}
    ports:
      - ${APP_SERVER_PORT}:${APP_SERVER_PORT}
    volumes: 
      - ./server/routes:/srv/app/phone-docker-server/routes
    command: 
      npm run dev
  client: 
    build: ./client
    environment: 
      - REACT_APP_PORT=${REACT_APP_PORT}
    expose: 
      - ${REACT_APP_PORT}
    ports:
      - ${REACT_APP_PORT}:${REACT_APP_PORT}
    volumes: 
      - ./client/src:/srv/app/phone-docker-client/src
      - ./client/public:/srv/app/phone-docker-client/public
    command: 
      npm start